/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_ysh_XLGame_HallLogicJni */

#ifndef _Included_com_android_ysh_XLGame_HallLogicJni
#define _Included_com_android_ysh_XLGame_HallLogicJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_ysh_XLGame_HallLogicJni
 * Method:    Init
 * Signature: (Ljava/lang/String;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_android_ysh_XLGame_HallLogicJni_Init
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_android_ysh_XLGame_HallLogicJni
 * Method:    LoginAsGuest
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_ysh_XLGame_HallLogicJni_LoginAsGuest
  (JNIEnv *, jobject);

/*
 * Class:     com_android_ysh_XLGame_HallLogicJni
 * Method:    GetDirInfo
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_com_android_ysh_XLGame_HallLogicJni_GetDirInfo
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_android_ysh_XLGame_HallLogicJni
 * Method:    QuerySuitRoom
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_android_ysh_XLGame_HallLogicJni_QuerySuitRoom
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_android_ysh_XLGame_HallLogicJni
 * Method:    EnterRoom
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_android_ysh_XLGame_HallLogicJni_EnterRoom
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_android_ysh_XLGame_HallLogicJni
 * Method:    AutoEnterGame
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_android_ysh_XLGame_HallLogicJni_AutoEnterGame
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_android_ysh_XLGame_HallLogicJni
 * Method:    GameReady
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_android_ysh_XLGame_HallLogicJni_GameReady
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     com_android_ysh_XLGame_HallLogicJni
 * Method:    QuitGame
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_android_ysh_XLGame_HallLogicJni_QuitGame
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_android_ysh_XLGame_HallLogicJni
 * Method:    ExitRoom
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_android_ysh_XLGame_HallLogicJni_ExitRoom
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_android_ysh_XLGame_HallLogicJni
 * Method:    SubmitGameAction
 * Signature: (I[BI)V
 */
JNIEXPORT void JNICALL Java_com_android_ysh_XLGame_HallLogicJni_SubmitGameAction
  (JNIEnv *, jobject, jint, jbyteArray, jint);

/*
 * Class:     com_android_ysh_XLGame_HallLogicJni
 * Method:    SetConfig
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_android_ysh_XLGame_HallLogicJni_SetConfig
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_android_ysh_XLGame_HallLogicJni
 * Method:    Replay
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_android_ysh_XLGame_HallLogicJni_Replay
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_android_ysh_XLGame_HallLogicJni
 * Method:    Uninit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_android_ysh_XLGame_HallLogicJni_Uninit
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
