/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>

/* Header for class ffmpegtest_Jni */

#define LOGI(logtag,infoMsg) __android_log_print(4,logtag,infoMsg)

#ifndef _CHESSLOGIC_JNI_H_
#define _CHESSLOGIC_JNI_H_
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     int com.ysh.android.ffmpegtest.Jni.getCInt()
 * Method:    getCInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ysh_chess_ChessLogicJNI_Call
  (JNIEnv *env, jobject thiz,jstring method,jint param1,jintArray param2);

JNIEXPORT jboolean JNICALL Java_com_ysh_chess_ChessLogicJNI_GetIsGameStarted
(JNIEnv *env, jobject thiz);

JNIEXPORT void JNICALL Java_com_ysh_chess_ChessLogicJNI_SetPracticeGameOver
(JNIEnv *env,jobject thiz);

JNIEXPORT jboolean JNICALL Java_com_ysh_chess_ChessLogicJNI_GetFlagSide
(JNIEnv *env, jobject thiz);

JNIEXPORT jboolean JNICALL Java_com_ysh_chess_ChessLogicJNI_GetIsMyTurn
(JNIEnv *env, jobject thiz);

JNIEXPORT jint JNICALL Java_com_ysh_chess_ChessLogicJNI_GetGameStatus
(JNIEnv *env, jobject thiz);

JNIEXPORT jboolean JNICALL Java_com_ysh_chess_ChessLogicJNI_GetStepCount
(JNIEnv *env, jobject thiz);

JNIEXPORT void JNICALL Java_com_ysh_chess_ChessLogicJNI_OnSvrRespSetGameOver
(JNIEnv *env, jobject thiz);

JNIEXPORT jint JNICALL Java_com_ysh_chess_ChessLogicJNI_GetPieceIndex 
(JNIEnv *env, jobject thiz,jint index,jint column);

JNIEXPORT jobjectArray JNICALL Java_com_ysh_chess_ChessLogicJNI_GetChessMap
(JNIEnv* env,jobject thiz); 

JNIEXPORT void JNICALL Java_com_ysh_chess_ChessLogicJNI_InitVM
(JNIEnv *env, jobject thiz, jobject b);

JNIEXPORT void JNICALL Java_com_ysh_chess_NetServer_OnGameActionNotify
(JNIEnv *env, jobject thiz,jlong UserID,jbyteArray szGameDataBuf);

JNIEXPORT void JNICALL Java_com_ysh_chess_NetServer_OnEndGameNotify
(JNIEnv *env,jobject thiz,jint TableID);


#ifdef __cplusplus
}
#endif
#endif
