
#ifndef __GAME_COMMAND_FACTORY_H_20090219_18
#define __GAME_COMMAND_FACTORY_H_20090219_18

#include "common/GameNetInf.h"

class GameCmdFactory
{
	GameCmdFactory() { }
public:
	enum ENUM_CMD_ID{
		CMD_ID_GETDIR = 100,
		CMD_ID_GETDIR_RESP = 101,
		CMD_ID_ENTERROOM = 200,
		CMD_ID_ENTERROOM_RESP = 201,
		CMD_ID_ENTERTABLE = 202,
		CMD_ID_ENTERTABLE_RESP = 203,
		CMD_ID_ASKSTART = 204,
		CMD_ID_ASKSTART_RESP = 205,
		CMD_ID_QUITGAME = 206,
		CMD_ID_QUITGAME_RESP = 207,
		CMD_ID_EXITROOM = 208,
		CMD_ID_EXITROOM_RESP = 209,
		CMD_ID_SUBMIT_ACTION = 210,
		CMD_ID_USERINFO_CHG_NOTIFY = 215,
		CMD_ID_USERSCORE_CHG_NOTIFY = 217,
		CMD_ID_USERSTATUS_CHG_NOTIFY = 219,
		CMD_ID_CHAT = 220,
		CMD_ID_CHAT_RESP = 221,
		CMD_ID_CHAT_NOTIFY = 223,
		CMD_ID_GAMEACTION_NOTIFY = 225,
		CMD_ID_KICKOUT = 229,
		CMD_ID_PING = 230,
		CMD_ID_PING_RESP = 231,
		CMD_ID_REPLAY = 234,
		CMD_ID_REPLAY_RESP = 235,
		CMD_ID_GAMESVR_DATAX = 236,
		CMD_ID_GAMESVR_DATAX_RESP = 237,

		CMD_ID_GETUSERGAMEINFO = 300,
		CMD_ID_GETUSERGAMEINFO_RESP = 301,
		CMD_ID_NONSESSION_DATAX = 306,
		CMD_ID_NONSESSION_DATAX_RESP = 307,
	
		CMD_ID_USERSTATUSSVR_DATAX = 400,
		CMD_ID_USERSTATUSSVR_DATAX_RESP = 401,

        CMD_ID_BALANCE_SVR_DATAX = 506,
        CMD_ID_BALANCE_SVR_DATAX_RESP = 507,


		CMD_ID_TIMED_MATCH_DATAX = 606,
		CMD_ID_TIMED_MATCH_DATAX_RESP = 607,

		CMD_ID_CHIP_SVR_DATAX = 616,
		CMD_ID_CHIP_SVR_DATAX_RESP = 617,

		CMD_ID_TABSTATUS_SVR_DATAX = 706,
		CMD_ID_TABSTATUS_SVR_DATAX_RESP = 707,

		CMD_ID_USERGUIDE_SVR_DATAX = 710,
		CMD_ID_USERGUIDE_SVR_DATAX_RESP = 711,

	};

public:
	static IGameCommand* create_cmd_by_typeid(short cmd_typeid);

private:
	DECL_LOGGER; //LOG4CPLUS_CLASS_DECLARE(s_logger);
};

#endif // #ifndef __GAME_COMMAND_FACTORY_H_20090219_18
